spring:
  application:
    name: rbpo-server
  datasource:
    url: jdbc:postgresql://localhost:5432/rbpo
    username: rbpo
    password: rbpo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
  security:
    require-ssl: true

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore/localhost.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: localhost
    key-password: password
    # УБИРАЕМ trust-store настройки
  http2:
    enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    ru.mtuci.rbposerver.filters.JwtRequestFilter: WARN

jwt:
  secret: RbpoSuperSecretKey123456789012345678901234567890
  access-jwt:
    expiration: 900000
  refresh-jwt:
    expiration: 604800000

management:
  security:
    enabled: false